Fixed "Does no exit" bug and miscellenous edits
sugarlabs/XOlympics pull request #10
Opened 2018-01-22 17:17 UTC by yashagrawal3

Fixes #8 
Fixes #9 

- added GTK version to be imported
- updated Sugargame/ files, it is now same as in similar activities
- removed "does not exit" bug

@quozl please review!

2018-01-22 17:20 UTC, yell0wfl4sh commented
Also, can you please add me as a maintainer in this activity so that I can release a new version. This willl also fix #2 , also to add, I got no response from previous maintainers.

2018-01-22 23:49 UTC, quozl commented
Invited.

https://github.com/sugarlabs/XOlympics/invitations

2018-01-22 23:55 UTC, quozl requested changes
Thanks.  Please use Sugargame v1.2?

2018-01-22 23:55 UTC, quozl commented on sugargame/canvas.py
> +        self._initialized = False
I've since removed this `self._initialized` in Sugargame, can you use the latest sources please?

2018-01-23 02:09 UTC, yashagrawal3 commented
Updated!

2018-01-23 02:57 UTC, merged